name: .NET 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
     
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish
      run: dotnet publish -r win-x64 --configuration Release
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServiceBusUtility
        path: "./ServiceBusUtility/bin/Release/net8.0/win-x64/publish"
        
        
    - name: Publish for Linx
      run: dotnet publish -r linux-x64 --configuration Release
    
    - name: Upload a Linux Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServiceBusUtility-linux
        path: "./ServiceBusUtility/bin/Release/net8.0/linux-x64/publish"
